version: "3.7"
services:
  longvinter-server:
    container_name: longvinter-server
    image: longvinter-linux-server
    build: .
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27016:27016/tcp"
      - "27016:27016/udp"
    environment:
      CFG_SERVER_NAME: "Unnamed Island"
      CFG_MAX_PLAYERS: "32"
      CFG_SERVER_MOTD: "Welcome to Longvinter Island!"
      CFG_PASSWORD: ""
      CFG_COMMUNITY_WEBSITE: "www.longvinter.com"
      CFG_ADMIN_STEAM_ID: ""
      CFG_ENABLE_PVP: "true"
      CFG_GAME_PORT: "7777"
      CFG_QUERY_PORT: "27016"
    volumes:
      - longvinter_data:/data
    restart: unless-stopped

volumes:
  longvinter_data:
    name: longvinter_data
  